import { Nunito_Sans } from "next/font/google";

import { config } from "@fortawesome/fontawesome-svg-core";

import ReduxProvider from "@/store/ReduxProvider";
import NextThemesProvider from "@/context/NextThemesProvider";
import NavbarTop from "@/layouts/NavbarTop";

import "@fortawesome/fontawesome-svg-core/styles.css";
import "../../public/scss/globals.scss";

const nunitoSans = Nunito_Sans({ subsets: ["latin"] });

config.autoAddCss = false;

export const metadata = {
  title: "Orbit",
  description: "Generated by create next app",
};

const RootLayout = ({ children }) => {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.lineicons.com/4.0/lineicons.css"
        />
      </head>
      <body className={nunitoSans.className}>
        <ReduxProvider>
          <NextThemesProvider>
            <NavbarTop />
            {children}
          </NextThemesProvider>
        </ReduxProvider>
      </body>
    </html>
  );
};

export default RootLayout;
