export const notificationData = [
  {
    avatar: "/img/users/1.webp",
    name: "Jessie Samson",
    description: "Mentioned you in a comment.",
    time: "10:41 AM",
    date: "August 7,2023",
    isRead: true,
  },
  {
    avatar: "/img/users/2.webp",
    name: "Jane Foster",
    description: "Created an event.",
    time: "10:20 AM",
    date: "August 7,2023",
    isRead: false,
  },
  {
    avatar: "/img/users/1.webp",
    name: "Jessie Samson",
    description: "Liked your comment.",
    time: "9:30 AM",
    date: "August 7,2023",
    isRead: false,
  },
  {
    avatar: "/img/users/4.webp",
    name: "Kiera Anderson",
    description: "Mentioned you in a comment.",
    time: "9:11 AM",
    date: "August 7,2023",
    isRead: false,
  },
  {
    avatar: "/img/users/5.webp",
    name: "Herman Carter",
    description: "Tagged you in a comment.",
    time: "10:58 PM",
    date: "August 6,2023",
    isRead: false,
  },
  {
    avatar: "/img/users/7.webp",
    name: "Benjamin Button",
    description: "Liked your comment.",
    time: "10:18 PM",
    date: "August 6,2023",
    isRead: false,
  },
];
